spring.application.name=aritoshi

# ===== サーバ設定 =====
server.port=8888

# ===== H2 Database設定 =====
# DB接続先URL
spring.datasource.url=jdbc:h2:mem:testdb 

# H2接続用ドライバ
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

# ===== H2 Console有効化 =====
# ブラウザからDB確認可能にする SQL実行やデーブル確認用
spring.h2.console.enabled=true

# ===== JPA設定 =====
# EntityからDBテーブルをどう生成するか
spring.jpa.hibernate.ddl-auto=update

# 実行SQLをログ表示
spring.jpa.show-sql=true